Repository vtex-apps/product-summary, pull requests merged in 2019-02, with the labels that each got.

#109 Fix Ramda isEmpty misuse
  CHANGELOG.md
  manifest.json
  react/components/ProductImage.js
Labels: bug

#84 Refactor buy button behavior and change storefront labels
  CHANGELOG.md
  manifest.json
  messages/en-US.json
  messages/es-AR.json
  messages/pt-BR.json
  react/__mocks__/@vtex/buy-button.js
  react/__mocks__/@vtex/product-details.js
  react/__mocks__/react-content-loader.js
  react/__mocks__/react-intl.js
  react/__mocks__/vtex.render-runtime.js
  react/__mocks__/vtex.store-components.js
  react/__mocks__/vtex.store-components/BuyButton.js
  react/__mocks__/vtex.store-components/ProductPrice.js
  react/__mocks__/vtex.store-resources/OrderFormContext/index.js
  react/__mocks__/vtex.styleguide/index.js
  react/__tests__/ProductSummary.test.js
  react/components/ProductSummaryBuyButton.js
  react/components/ProductSummaryNormal.js
  react/package.json
  react/setupTests.js
  react/yarn.lock
  yarn.lock
Labels: bug

#111 Fix Product Summary information space
  CHANGELOG.md
  manifest.json
  react/components/ProductSummaryNormal.js
Labels: bug

#113 Remove fixed width and horizontal paddings
  CHANGELOG.md
  manifest.json
  react/components/ProductSummaryNormal.js
  react/components/ProductSummarySmall.js
  react/productSummary.css
Labels: breaking-change

#112 Update BuyButton items props to use the Minicart's optimistic strategy
  CHANGELOG.md
  manifest.json
  react/components/ProductSummaryBuyButton.js
Labels: enhancement
