Repository vtex-apps/product-summary, pull requests merged in 2019-01, with the labels that each got.

#80 Bye pages.json! Welcome store-builder
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  manifest.json
  pages/pages.json
  react/index.js
  store/blocks.json
  store/interfaces.json
Labels: enhancement

#87 Remove undefined css classes
  CHANGELOG.md
  manifest.json
  react/index.js
  react/productSummary.css
Labels: bug

#85 Improve HTML code quality [product-summary]
  CHANGELOG.md
  manifest.json
  react/index.js
Labels: chore

#100 Extract components for a better reuse
  CHANGELOG.md
  manifest.json
  react/components/ImageLoader.js
  react/components/ProductImage.js
  react/components/ProductSummaryName.js
  react/components/ProductSummaryPrice.js
  react/index.js
Labels: chore
